apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-one-deployment
  labels:
    app: microservice-one
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-one
  template:
    metadata:
      labels:
        app: microservice-one
    spec:
      containers:
      - name: microservice-one
        image: mikeskuse/microservice-one:0.1.12 
        ports:
        - containerPort: 8001