version: 2
jobs:
  build:
    working_directory: ~/mern-starter
    # The primary container is an instance of the first image listed. The job's commands run in this container.
    docker:
      - image: mikeskuse/buildimage
    steps:
      - checkout
      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t mikeskuse/microservice-one:$TAG  -t mikeskuse/microservice-one:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push mikeskuse/microservice-one:latest